[theme]
base = "light"
primaryColor = "#f97316"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#09090b"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
